export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const SET_INFO_MESSAGE = 'SET_INFO_MESSAGE';
export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE';
export const SET_FETCHING_REQUEST = 'SET_FETCHING_REQUEST';
export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const GET_UFS_SUCCESS = 'GET_UFS_SUCCESS';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';

export const GET_TABLE_HEAD_SUCCESS = 'GET_TABLE_HEAD_SUCCESS';
export const SET_PERSON_FORM = 'SET_PERSON_FORM';
export const SET_EDITING_PERSON = 'SET_EDITING_PERSON';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PERSON_SUCCESS = 'GET_PERSON_SUCCESS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_ROWS_PER_PAGE = 'CHANGE_ROWS_PER_PAGE';
export const RESET_PERSON = 'RESET_PERSON';
